[package]
name = "scale-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "2.0.0-rc.4"
image = "0.25"
thiserror = "1.0"
ndarray = "0.16"

[dev-dependencies]
criterion = "^0.5"

[[bench]]
name = "devbench"
harness = false
