[package]
name = "scale-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
thiserror = "1.0"

[dev-dependencies]
criterion = "^0.5"

[[bench]]
name = "devbench"
harness = false